project_id = "nwgomximjevgczwuyqcx"

[functions.process-cancellation]
verify_jwt = true

[functions.automated-billing]
verify_jwt = false

[functions.send-class-report-notification]
verify_jwt = true

[functions.setup-billing-automation]
verify_jwt = true

[functions.create-student]
verify_jwt = true

[functions.create-connect-account]
verify_jwt = true

[functions.create-connect-onboarding-link]
verify_jwt = true

[functions.create-payment-intent-connect]
verify_jwt = false

[functions.generate-boleto-for-invoice]
verify_jwt = false

[functions.webhook-stripe-connect]
verify_jwt = false

[functions.webhook-stripe-subscriptions]
verify_jwt = false
